name: Deploy Both Sites

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # -----------------
      # BUILD COLLECTIVE VERSION
      # -----------------
      - name: Build Collective
        run: npm run build:collective

      - name: Deploy to holiccollective-convention
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          external_repository: karuto/holiccollective-convention
          publish_branch: gh-pages
          publish_dir: ./dist

      # -----------------
      # BUILD PERSONAL VERSION
      # -----------------
      - name: Clean dist
        run: rm -rf dist

      - name: Build Personal
        run: npm run build:personal

      - name: Deploy to holiccollective-con-app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
